default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: tech_advisors_dev

test:
  <<: *default
  database: tech_advisors_test
